### ISSUE TITLE
Mapa mental; comunicacion oral y escrita; Emmanuel Marx Salazar González 1BS

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-marxgonzalez29#1]
![mapa mental; comunicacion oral y escrita](https://user-images.githubusercontent.com/112300981/191447109-16024098-bde3-424f-b48c-22fa664b672b.jpg)

**Comment by Jaczibeth** [comment]
Obtuviste un 10% del 20%
Ya que no cuenta con  la información solicitada.
Trabajar en la estructura del mapa mental.

**Comment by josealfredo79** [comment]
Favor de realizar y reestructurar el mapa mental por favor

**Comment by josealfredo79** [comment]
Calificacion: 15

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
